services:
  postgres:
    image: postgres:16
    container_name: postgres_petdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: petDB
      POSTGRES_PASSWORD: cWjxWoosUZxljCBmorNBAIpv4OX8VMWE
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data